### ISSUE TITLE
WebSocket auto reconnect on disconnect would be very helpful.

### ISSUE THREAD

**Issue by arreehm** [ViewBlock/binance-api-node#621]
Websockets sometimes disconnects, but all we want to is to keep them open.

**Comment by htotoo** [comment]
For example the ws.candles don't reconnects.
Indeed would be a life saver.

**Comment by ne0c0de** [comment]
I really don't understand how is the most popular nodejs library has doesn't have this feature. There are a lot of issues written on here but still no solution.

I think it's time to switch to another library..

**Comment by balthazar** [comment]
We already use [reconnecting-websocket](https://github.com/ViewBlock/binance-api-node/blob/master/src/open-websocket.js#L7) to handle websocket connections already. I'm guessing you guys should tweak the passed options (most notably the connectionTimeout in case you have spotty connections).
