### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by Vasile-Peste** [ViewBlock/binance-api-node#628]
Hello, what about adding a changelog to this project?

Regards,
Vasile

**Comment by balthazar** [comment]
Will you maintain it?

**Comment by Vasile-Peste** [comment]
> Will you maintain it?

What do you mean?
What kind of maintenance is needed for adding a changelog line before merging a PR? 🤔

**Comment by balthazar** [comment]
Maybe once you start making public repositories used by people you'll understand.

**Comment by Vasile-Peste** [comment]
Maybe you can learn from here https://github.com/tiagosiebler/binance
but with this attitude I doubt you can
